### ISSUE TITLE
Compile error - Threadripper Pro

### ISSUE THREAD

**Issue by brianwfreeman** [harold-b/bladebit#11]
src/platform/linux/SysHost_Linux.cpp:9:10: fatal error: numa.h: No such file or directory
    9 | #include <numa.h>
      |          ^~~~~~~~
compilation terminated.

**Comment by harold-b** [comment]
Haven’t updated the readme with dependencies, but you need to install libnuma-dev or numaclt-devel or whatever the equivalent on your distro
