### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by wsobrinho** [harold-b/bladebit#13]
src/platform/linux/SysHost_Linux.cpp:9:10: fatal error: numa.h: No such file or directory
    9 | #include <numa.h>
      |          ^~~~~~~~
src/util/Log.cpp
compilation terminated.
make: *** [Makefile:190: .obj/platform/linux/SysHost_Linux.o] Error 1
make: *** Waiting for unfinished jobs....

**Comment by harold-b** [comment]
Please see https://github.com/harold-b/bladebit/issues/11

**Comment by wsobrinho** [comment]
Thank you Harold,
Sorry this is my first contact with c++ i am from C# world.

**Comment by harold-b** [comment]
No worries at all! No need to apologize 🙂
