### ISSUE TITLE
make error on Centos 7

### ISSUE THREAD

**Issue by grobalt** [harold-b/bladebit#16]
[~/bladebit]: make clean && make -j$(nproc --all)
src/b3/blake3_avx2_x86-64_unix.S
Compiling for linux with g++
src/b3/blake3_avx512_x86-64_unix.S
src/b3/blake3_dispatch.c
src/b3/blake3_portable.c
src/b3/blake3_sse41_x86-64_unix.S
src/b3/blake3.c
src/bech32/segwit_addr.c
src/fse/debug.c
src/fse/entropy_common.c
src/fse/fse_compress.c
src/fse/fse_decompress.c
src/fse/hist.c
src/io/FileStream.cpp
src/main.cpp
src/memplot/DbgHelper.cpp
src/memplot/MemPhase1.cpp
src/memplot/MemPhase2.cpp
src/memplot/MemPhase3.cpp
src/memplot/MemPhase4.cpp
src/memplot/MemPlotter.cpp
src/pch.cpp
src/platform/linux/SysHost_Linux.cpp
src/platform/unix/FileStream_Unix.cpp
src/PlotContext.cpp
src/PlotWriter.cpp
src/pos/chacha8.cpp
src/SysHost.cpp
src/threading/Semaphore.cpp
src/threading/Thread.cpp
src/threading/ThreadPool.cpp
src/Util.cpp
src/util/Log.cpp
lib/linux/x86/libbls.a(relic_bn_add_low.c.o): In function `bn_addn_low':
relic_bn_add_low.c:(.text+0x414): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_bn_add_low.c.o): In function `bn_subn_low':
relic_bn_add_low.c:(.text+0x844): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_bn_mod_low.c.o): In function `bn_modn_low':
relic_bn_mod_low.c:(.text+0x163): undefined reference to `__gmpn_addmul_1'
relic_bn_mod_low.c:(.text+0x180): undefined reference to `__gmpn_addmul_1'
relic_bn_mod_low.c:(.text+0x19d): undefined reference to `__gmpn_addmul_1'
relic_bn_mod_low.c:(.text+0x1bb): undefined reference to `__gmpn_addmul_1'
relic_bn_mod_low.c:(.text+0x1d5): undefined reference to `__gmpn_addmul_1'
lib/linux/x86/libbls.a(relic_bn_mod_low.c.o):relic_bn_mod_low.c:(.text+0x1f0): more undefined references to `__gmpn_addmul_1' follow
lib/linux/x86/libbls.a(relic_bn_mod_low.c.o): In function `bn_modn_low':
relic_bn_mod_low.c:(.text+0x229): undefined reference to `__gmpn_add_n'
relic_bn_mod_low.c:(.text+0x263): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_bn_mul_low.c.o): In function `bn_mula_low':
relic_bn_mul_low.c:(.text+0xa): undefined reference to `__gmpn_addmul_1'
lib/linux/x86/libbls.a(relic_bn_mul_low.c.o): In function `bn_mul1_low':
relic_bn_mul_low.c:(.text+0x1a): undefined reference to `__gmpn_mul_1'
lib/linux/x86/libbls.a(relic_bn_mul_low.c.o): In function `bn_muln_low':
relic_bn_mul_low.c:(.text+0x24): undefined reference to `__gmpn_mul_n'
lib/linux/x86/libbls.a(relic_bn_mul_low.c.o): In function `bn_muld_low':
relic_bn_mul_low.c:(.text+0x37): undefined reference to `__gmpn_mul'
lib/linux/x86/libbls.a(relic_bn_shift_low.c.o): In function `bn_lsh1_low':
relic_bn_shift_low.c:(.text+0x9): undefined reference to `__gmpn_lshift'
lib/linux/x86/libbls.a(relic_bn_shift_low.c.o): In function `bn_lshb_low':
relic_bn_shift_low.c:(.text+0x14): undefined reference to `__gmpn_lshift'
lib/linux/x86/libbls.a(relic_bn_shift_low.c.o): In function `bn_rsh1_low':
relic_bn_shift_low.c:(.text+0x29): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_bn_shift_low.c.o): In function `bn_rshb_low':
relic_bn_shift_low.c:(.text+0x34): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_fb_add_low.c.o): In function `fb_addn_low':
relic_fb_add_low.c:(.text+0x36): undefined reference to `__gmpn_xor_n'
lib/linux/x86/libbls.a(relic_fb_add_low.c.o): In function `fb_addd_low':
relic_fb_add_low.c:(.text+0x44): undefined reference to `__gmpn_xor_n'
lib/linux/x86/libbls.a(relic_fb_shift_low.c.o): In function `fb_lsh1_low':
relic_fb_shift_low.c:(.text+0xb): undefined reference to `__gmpn_lshift'
lib/linux/x86/libbls.a(relic_fb_shift_low.c.o): In function `fb_lshb_low':
relic_fb_shift_low.c:(.text+0x18): undefined reference to `__gmpn_lshift'
lib/linux/x86/libbls.a(relic_fb_shift_low.c.o): In function `fb_rsh1_low':
relic_fb_shift_low.c:(.text+0x2b): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_fb_shift_low.c.o): In function `fb_rshb_low':
relic_fb_shift_low.c:(.text+0x38): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_addm_low':
relic_fp_add_low.c:(.text+0x11a): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_addc_low':
relic_fp_add_low.c:(.text+0x18e): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_subm_low':
relic_fp_add_low.c:(.text+0x31a): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_subc_low':
relic_fp_add_low.c:(.text+0x36a): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_dblm_low':
relic_fp_add_low.c:(.text+0x40d): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_hlvm_low':
relic_fp_add_low.c:(.text+0x479): undefined reference to `__gmpn_add_n'
relic_fp_add_low.c:(.text+0x491): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_hlvd_low':
relic_fp_add_low.c:(.text+0x515): undefined reference to `__gmpn_add_n'
relic_fp_add_low.c:(.text+0x58c): undefined reference to `__gmpn_rshift'
relic_fp_add_low.c:(.text+0x5a4): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_addn_low':
relic_fp_add_low.c:(.text+0x106): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_addm_low':
relic_fp_add_low.c:(.text+0x152): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_addd_low':
relic_fp_add_low.c:(.text+0x176): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_addc_low':
relic_fp_add_low.c:(.text+0x1c6): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_subn_low':
relic_fp_add_low.c:(.text+0x306): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_subm_low':
relic_fp_add_low.c:(.text+0x33d): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_subd_low':
relic_fp_add_low.c:(.text+0x356): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_subc_low':
relic_fp_add_low.c:(.text+0x38e): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_negm_low':
relic_fp_add_low.c:(.text+0x3ea): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_dbln_low':
relic_fp_add_low.c:(.text+0x3f9): undefined reference to `__gmpn_add_n'
lib/linux/x86/libbls.a(relic_fp_add_low.c.o): In function `fp_hlvm_low':
relic_fp_add_low.c:(.text+0x4d1): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_fp_inv_low.c.o): In function `fp_invm_low':
relic_fp_inv_low.c:(.text+0x81): undefined reference to `__gmpn_gcdext'
relic_fp_inv_low.c:(.text+0xe0): undefined reference to `__gmpn_tdiv_qr'
relic_fp_inv_low.c:(.text+0x11e): undefined reference to `__gmpn_sub_n'
lib/linux/x86/libbls.a(relic_fp_mul_low.c.o): In function `fp_mula_low':
relic_fp_mul_low.c:(.text+0x9): undefined reference to `__gmpn_addmul_1'
lib/linux/x86/libbls.a(relic_fp_mul_low.c.o): In function `fp_mul1_low':
relic_fp_mul_low.c:(.text+0x19): undefined reference to `__gmpn_mul_1'
lib/linux/x86/libbls.a(relic_fp_mul_low.c.o): In function `fp_muln_low':
relic_fp_mul_low.c:(.text+0x26): undefined reference to `__gmpn_mul_n'
lib/linux/x86/libbls.a(relic_fp_rdc_low.c.o): In function `fp_rdcn_low':
relic_fp_rdc_low.c:(.text+0x527): undefined reference to `__gmpn_addmul_1'
lib/linux/x86/libbls.a(relic_fp_shift_low.c.o): In function `fp_lsh1_low':
relic_fp_shift_low.c:(.text+0xb): undefined reference to `__gmpn_lshift'
lib/linux/x86/libbls.a(relic_fp_shift_low.c.o): In function `fp_lshb_low':
relic_fp_shift_low.c:(.text+0x18): undefined reference to `__gmpn_lshift'
lib/linux/x86/libbls.a(relic_fp_shift_low.c.o): In function `fp_rsh1_low':
relic_fp_shift_low.c:(.text+0x2b): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_fp_shift_low.c.o): In function `fp_rshb_low':
relic_fp_shift_low.c:(.text+0x38): undefined reference to `__gmpn_rshift'
lib/linux/x86/libbls.a(relic_fp_sqr_low.c.o): In function `fp_sqrn_low':
relic_fp_sqr_low.c:(.text+0x9): undefined reference to `__gmpn_mul_n'
lib/linux/x86/libbls.a(relic_bn_div_low.c.o): In function `bn_divn_low':
relic_bn_div_low.c:(.text+0x15): undefined reference to `__gmpn_tdiv_qr'
lib/linux/x86/libbls.a(relic_bn_div_low.c.o): In function `bn_div1_low':
relic_bn_div_low.c:(.text+0x2a): undefined reference to `__gmpn_divrem_1'
lib/linux/x86/libbls.a(relic_bn_sqr_low.c.o): In function `bn_sqra_low':
relic_bn_sqr_low.c:(.text+0x28): undefined reference to `__gmpn_addmul_1'
relic_bn_sqr_low.c:(.text+0x52): undefined reference to `__gmpn_addmul_1'
lib/linux/x86/libbls.a(relic_bn_sqr_low.c.o): In function `bn_sqrn_low':
relic_bn_sqr_low.c:(.text+0x87): undefined reference to `__gmpn_mul_n'
collect2: error: ld returned 1 exit status
make: *** [Makefile:157: bladebit] Error 1

**Comment by harold-b** [comment]
This is probably GCC 11 which BLS/Relic does not support.

**Comment by harold-b** [comment]
You can try to an earlier version of GCC, or see my comment [here](https://github.com/harold-b/bladebit/pull/14) about pointing the submodule to computer_whisper's fork of BLS. Let me know if you need more help.

**Comment by grobalt** [comment]
Centos 7 default is:
g++ --version
g++ (GCC) 8.4.1 20200928 (Red Hat 8.4.1-1)

**Comment by harold-b** [comment]
Looking at it more closely, you might be missing libgmp.

**Comment by harold-b** [comment]
Closing here if there's nothing else to be said.
