### ISSUE TITLE
./bladebit: No such file or directory

### ISSUE THREAD

**Issue by puffytr** [harold-b/bladebit#19]
I did all the installations. I didn't get any errors. Can someone tell me where I went wrong?

OS: Ubuntu 20.04

**Comment by alext2020** [comment]
I too facing this error after I follow step by step installation... 
Anyone can help to guide us? We are very much interested to test and feedback on the wonderful work by Harold-b?

**Comment by mocksoul** [comment]
Try ./.bin/release/bladebit ;-)

**Comment by puffytr** [comment]
> Try `./.bin/release/bladebit` ;-)

Thanks. it's worked.
