### ISSUE TITLE
Error installing on ubantu20.04

### ISSUE THREAD

**Issue by drake618** [harold-b/bladebit#20]
make clean && make -j$(nproc --all) #The echo of executing this command is as follows:

ubantu@ubantu-X99:~/bladebit$ make clean && make -j$(nproc --all)
Compiling for linux with g++
src/b3/blake3_avx2_x86-64_unix.S
src/b3/blake3_avx512_x86-64_unix.S
src/b3/blake3_dispatch.c
src/b3/blake3_portable.c
src/b3/blake3_sse41_x86-64_unix.S
src/b3/blake3.c
src/bech32/segwit_addr.c
src/fse/debug.c
src/fse/entropy_common.c
src/fse/fse_compress.c
src/fse/fse_decompress.c
src/fse/hist.c
src/io/FileStream.cpp
src/main.cpp
src/memplot/DbgHelper.cpp
src/memplot/MemPhase1.cpp
src/memplot/MemPhase2.cpp
src/memplot/MemPhase3.cpp
src/memplot/MemPhase4.cpp
src/memplot/MemPlotter.cpp
src/pch.cpp
src/platform/linux/SysHost_Linux.cpp
src/platform/unix/FileStream_Unix.cpp
src/PlotContext.cpp
src/PlotWriter.cpp
src/pos/chacha8.cpp
src/SysHost.cpp
src/threading/Semaphore.cpp
src/threading/Thread.cpp
src/threading/ThreadPool.cpp
src/Util.cpp
src/util/Log.cpp
src/platform/linux/SysHost_Linux.cpp:9:10: fatal error: numa.h: There is no file or directory
    9 | #include <numa.h>
      |          ^~~~~~~~
compilation terminated.
make: *** [Makefile:190：.obj/platform/linux/SysHost_Linux.o] error 1
make: *** Waiting for unfinished tasks....

**Comment by alext2020** [comment]
Does anyone kind enough to publish step by step installation and plotting guide on Ubuntu 20.04? Very appreciated....Thanks a million

**Comment by puffytr** [comment]
you need to install libnuma-dev or numaclt-devel

**Comment by puffytr** [comment]
#11 Same error.

**Comment by wsobrinho** [comment]
This wil work:
 # install build toolkit and NUMA library
  sudo apt update && sudo apt install cmake build-essential libnuma-dev -y
