### ISSUE TITLE
Cannot compile Amazon r6gd.metal ARM Ubuntu 20.04

### ISSUE THREAD

**Issue by puffytr** [harold-b/bladebit#23]
![image](https://user-images.githubusercontent.com/57060480/126357346-bb313f71-31d9-4a13-97a1-3aef448ef6e2.png)
![image](https://user-images.githubusercontent.com/57060480/126357417-c894553b-7e23-4993-914e-205ac18c4408.png)

**Comment by harold-b** [comment]
I can't see any errors displayed there, (I see a warning, though :) ), but I will assume it is the same issues with BLS and newer versions of clang. If you are using any of AWS's ARM instances, I'd use Amazon Linux, (in which this was developed) as it performed faster in my testing). But, if you'd like to go with Ubuntu, see my comment here: https://github.com/harold-b/bladebit/pull/14
You can clone that version of BLS meanwhile.

**Comment by puffytr** [comment]
Not used to it as I haven't used Amazon Linux before. I've never used Centos before. I have always used ubuntu. So I want to go over ubuntu. How we can solve this problem? All required libraries are installed.

**Comment by harold-b** [comment]
See the comment I mentioned previously. You can point the submodule to computer_whisperer's BLS fork which works in contemporary versions of GCC.

**Comment by harold-b** [comment]
Let me know if you got it working or need more details.

**Comment by harold-b** [comment]
Closing here if there's nothing else to be said.

**Comment by hishboy** [comment]
<img width="719" alt="image" src="https://user-images.githubusercontent.com/340982/126735812-05796f65-302f-4366-9fc9-206b55016014.png">

here's the error I'm seeing on ubuntu

**Comment by harold-b** [comment]
You need to install your distro's numa development libs, which in Ubuntu I believe is `libnuma-dev`.
