### ISSUE TITLE
" Waiting for last plot to finish being written to disk..."

### ISSUE THREAD

**Issue by terrancewong** [harold-b/bladebit#26]
if I have more than 416+101GiB RAM, and disk throughput faster than plotting, there's no need to wait for last plot to be written. performance impact should be less than doing nothing but waiting.

**Comment by harold-b** [comment]
> and disk throughput faster than plotting

Evidently not, otherwise you wouldn't hit the wait period.

**Comment by terrancewong** [comment]
typical server takes 5-15min to plot. typical HDD write throughput >= 200MB/s, takes ~10min to write 108GB, write a simple command line can spread writes to 2-3 HDDs. how about make that waiting opt out?
