### ISSUE TITLE
Use same filename format for plots

### ISSUE THREAD

**Issue by hishboy** [harold-b/bladebit#29]
I just did a quick run and it seems like the file name doesn't match chia's standard plot naming convention. Is it possible to match it? It would really help with some of the infra folks are building.

**Comment by harold-b** [comment]
Thanks for the suggestion, there's an issue already open about this: https://github.com/harold-b/bladebit/issues/3
And a community member has opened a PR to implement that here: https://github.com/harold-b/bladebit/pull/21

I was hoping to review it yesterday, but unfortunately did not have time. I'll try to do so this weekend.

**Comment by harold-b** [comment]
Closing as it is a dupicate
