### ISSUE TITLE
Suggestions: final plot name match to standard format

### ISSUE THREAD

**Issue by paspy** [harold-b/bladebit#3]
It works perfect on my spec, thanks for the contribution to the Chia community!

It will be good to match the standard plot name like: plot-k32-{YYYY}-{MM}-{DD}-{hh}-{mm}-xxxx.plot

**Comment by harold-b** [comment]
Thanks for the suggestion, and good point. I have not added much in terms of quality of life, but this is probably the first to be done along with having the files have a tmp extension before they are fully written.

**Comment by laudney** [comment]
without the prefix of _plot-k32-{YYYY}-{MM}-{DD}-{hh}-{mm}_, the plot file doesn't seem to be picked up by harvesters which rely on parsing plot file names to get the plot ID.

**Comment by mocksoul** [comment]
> without the prefix of _plot-k32-{YYYY}-{MM}-{DD}-{hh}-{mm}_, the plot file doesn't seem to be picked up by harvesters which rely on parsing plot file names to get the plot ID.

this is wrong. My harvesters grab all *.plot files including these


but if u want -- this is quick&dirty patch to add prefix and also write originally .tmp file and move to .plot once generation finished.

`diff --git a/src/main.cpp b/src/main.cpp
index 2840e83..24d7579 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -102,7 +102,15 @@ int main( int argc, const char* argv[] )

     // Create the plot output path
     size_t outputFolderLen = strlen( cfg.outputFolder );
-    char* plotOutPath = new char[outputFolderLen + 64+6+1];
+    //char* plotOutPath = new char[outputFolderLen + 64+6+1];
+    // initial dir sep == 1
+    // plot-k32 == 8
+    // +1 sep
+    // ymdhm is 4+2+2+2+2 + 4 separators == 16
+    // +1 sep
+    // plotid
+    // .plot.tmp == 9
+    char* plotOutPath = new char[outputFolderLen + 1+8+1+16+1+64+9+1];

     if( outputFolderLen )
     {
@@ -113,8 +121,11 @@ int main( int argc, const char* argv[] )
             plotOutPath[outputFolderLen++] = '/';
     }

-    memcpy( plotOutPath+outputFolderLen+64, ".plot", sizeof( ".plot" ) );
-
+    time_t now = time(NULL);
+    struct tm *t = localtime(&now);
+    strftime(plotOutPath+outputFolderLen, outputFolderLen + 99 + 1, "plot-k32-%Y-%m-%d-%H-%M-", t);
+
+    memcpy( plotOutPath+outputFolderLen+26+64, ".plot.tmp", sizeof( ".plot.tmp" ) );

diff --git a/src/memplot/MemPhase1.cpp b/src/memplot/MemPhase1.cpp
index 3af2e6f..45dd47e 100644
--- a/src/memplot/MemPhase1.cpp
+++ b/src/memplot/MemPhase1.cpp
@@ -101,6 +101,12 @@ void MemPhase1::WaitForPreviousPlotWriter()
             _context.plotWriter->FilePath().c_str(),
             _context.plotWriter->GetError() );

+    const char* curname = _context.plotWriter->FilePath().c_str();
+    char* newname = new char[strlen(curname) - 4];
+    memcpy(newname, curname, strlen(curname) - 4);
+
+    rename(curname, newname);
+
     // Print final pointer offsets
     Log::Line( "" );
     Log::Line( "Previous plot %s finished writing to disk:", _context.plotWriter->FilePath().c_str() );
diff --git a/src/memplot/MemPlotter.cpp b/src/memplot/MemPlotter.cpp
index 52ad9ed..2174d65 100644
--- a/src/memplot/MemPlotter.cpp
+++ b/src/memplot/MemPlotter.cpp
@@ -221,6 +221,12 @@ void MemPlotter::WaitPlotWriter()
                 _context.plotWriter->FilePath().c_str(),
                 _context.plotWriter->GetError() );

+        const char* curname = _context.plotWriter->FilePath().c_str();
+        char* newname = new char[strlen(curname) - 4];
+        memcpy(newname, curname, strlen(curname) - 4);
+
+        rename(curname, newname);
+
         // Print final pointer offsets
         Log::Line( "" );
         Log::Line( "Plot %s finished writing to disk:", _context.plotWriter->FilePath().c_str() );

`

**Comment by harold-b** [comment]
Fixed by #21
