### ISSUE TITLE
how to use it on command line？

### ISSUE THREAD

**Issue by soldier-9527** [harold-b/bladebit#39]
I compile it， and I can't use it，can not find command

**Comment by CharlieTemplar** [comment]
gets built to :
`../.bin/release/bladebit`
run it with -h for usage.

**Comment by trs-80** [comment]
The binary, in relation to the build directory, is in ```.bin/release/bladebit```

Here is a bash script I use to run it from the build directory:
```
#!/bin/bash
CHIA_CONTRACT="your_contract_id_here"
CHIA_FARMER="your_farmer_id_here"
DATE=$(date '+%Y-%m-%d')
N=1
W="-w"

./.bin/release/bladebit ${W} -n ${N} \
    \-c ${CHIA_CONTRACT} \
    \-f ${CHIA_FARMER} \
    /EDIT-your_destination_directory/ \
| tee -a ~/bladebit_plotlog\_${DATE}\.log
```

Note the above assumes you are plotting to a pool and not solo farming

**Comment by xch-pet** [comment]
### Can't use ### 

I'm in `~/bladebit/.bin/release`
contents are here:
`user:~/bladebit/.bin/release$ ls`
`bladebit  bladebit.debug`

I try to run `bladebit -h`
I get:
bladebit: command not found 

It compiled without error... What am I missing?

**Comment by soldier-9527** [comment]
> ### Can't use
> I'm in `~/bladebit/.bin/release`
> contents are here:
> `user:~/bladebit/.bin/release$ ls`
> `bladebit bladebit.debug`
> 
> I try to run `bladebit -h`
> I get:
> bladebit: command not found
> 
> It compiled without error... What am I missing?

./beadebit -h

**Comment by xch-pet** [comment]
> > ### Can't use
> > I'm in `~/bladebit/.bin/release`
> > contents are here:
> > `user:~/bladebit/.bin/release$ ls`
> > `bladebit bladebit.debug`
> > I try to run `bladebit -h`
> > I get:
> > bladebit: command not found
> > It compiled without error... What am I missing?
> 
> ./beadebit -h

*bangs head on desk*

**Comment by harold-b** [comment]
Closing since community came to the rescue. 
Anything further [here](https://github.com/harold-b/bladebit/discussions).
