### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by oxidized-vizit** [harold-b/bladebit#47]
Hello!
I tried install Bladebit on r6g.metal and r6g.16xlarge instance (ARM), but I can't compile it. I try Ubuntu 20LTS, RedHat 8, Amazon-linux, but every time I have the next error:

> make clean && make -j$(nproc --all) CONFIG=release.arm
> ....
> ....
> src/util/Log.cpp
> In function ‘memcpy’,
>     inlined from ‘compress_parents_parallel’ at src/b3/blake3.c:242:5,
>     inlined from ‘compress_subtree_to_parent_node’ at src/b3/blake3.c:355:9,
>     inlined from ‘blake3_hasher_update.part.0’ at src/b3/blake3.c:534:7:
> /usr/include/aarch64-linux-gnu/bits/string_fortified.h:34:10: warning: ‘__builtin_memcpy’ writing 32 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
>    34 |   return __builtin___memcpy_chk (__dest, __src, __len, __bos0 (__dest));
>       |          ^

cmake --version
cmake version 3.16.3

gcc --version
gcc (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

Previously I tried gcc 9.

Thanks!

**Comment by harold-b** [comment]
This is a warning, not a fatal error. Are you actually getting an error not shown here?
