### ISSUE TITLE
plz, help a noob with install cmnds on  ubuntu 

### ISSUE THREAD

**Issue by ari2asem** [harold-b/bladebit#48]
i am sorry for my noob question as i am totally new to Linux (using ubuntu 20.04).

i would like to know which commands to use to install all needed packets/files on ubuntu.

plz, provide  full commands. not some parts of it.

thanks in advance

**Comment by valiDol42** [comment]
# install all needed
sudo apt install cmake -y
sudo apt-get install libnuma-dev build-essential -y

# Clone the repo & its submodules
git clone --recursive https://github.com/harold-b/bladebit.git

cd bladebit

# Build bls library. Only needs to be done once.
./build-bls

# For x86
make clean && make -j$(nproc --all)

~/bladebit/.bin/release/bladebit -f YourFarmerKey -c Your_pool_contract_address_for_plotting -n 100 -w /mnt/final

**Comment by ari2asem** [comment]
the -w is for wait for 2nd plotting before the finel plot is transfered to final directory ??

**Comment by valiDol42** [comment]
-w, --warm-start     : Touch all pages of buffer allocations before starting to plot.

**Comment by ari2asem** [comment]
> 
> 
> 
> # For x86
> make clean && make -j$(nproc --all)
> 
when i enter this command, i get error:
numa.h  no such file or directory.
this numa.h gets called from /src/platform/linux/SysHost_Linux.cpp

@harold-b  can you fix this error ??

**Comment by valiDol42** [comment]
> > # For x86
> > make clean && make -j$(nproc --all)
> 
> when i enter this command, i get error:
> numa.h no such file or directory.
> this numa.h gets called from /src/platform/linux/SysHost_Linux.cpp
> 
> @harold-b can you fix this error ??

sudo apt-get install libnuma-dev

**Comment by harold-b** [comment]
Closing as community came to the rescue.
Further questions/discussions [here](https://github.com/harold-b/bladebit/discussions) please.
