### ISSUE TITLE
Add ".tmp" to plot file name until after final write to disk

### ISSUE THREAD

**Issue by depasseg** [harold-b/bladebit#58]
I noticed that a 0 byte file is created at the beginning of the process and that is the final plot file name.  It would be helpful if there was a way to differentiate between final/completed plots, and ones that were still in progress so that I can run rsync to migrate the finished plots.

Adding an extension like ".tmp" at the beginning of hte process and then removing it after the plot file is actually done would help this automated tiered storage move process.

**Comment by icsta** [comment]
If you get the latest code it does add .tmp at the end of the file name.

**Comment by harold-b** [comment]
Closing because, as specified by @icsta, this was implemented in #21 and has been merged to master.
