### ISSUE TITLE
Pool plots invalid?

### ISSUE THREAD

**Issue by preutrn** [harold-b/bladebit#7]
Just wondering if anyone had luck with pool plots.
I've plotted couple dozens but the farmer rejects every single proof-of-space from those plots. Keep getting errors like that:

```
2021-07-15T15:20:35.154 farmer farmer_server              : DEBUG    <- new_proof_of_space from peer <harvester-id> <harvester ip>
2021-07-15T15:20:35.155 farmer farmer_server              : DEBUG    <- farming_info from peer <harvester-id> <harvester ip>
2021-07-15T15:20:35.155 farmer chia.types.blockchain_format.proof_of_space: ERROR    New challenge is not challenge
2021-07-15T15:20:35.155 farmer chia.farmer.farmer         : ERROR    Invalid proof of space {'challenge': '0x6a0acd1b438102dd8baede36df56bc7ec5177bf1b22fac97b97c94bb6e406b73',
 'plot_public_key': '0x<plot key>',
 'pool_contract_puzzle_hash': '0x<correct puzzle hash>',
 'pool_public_key': None,
 'proof': '0x<long-long-proof>',
 'size': 32}
```
 
I've double- and triple-checked the arguments (i.e. farmer key) and they are definitely correct.
I've done `chia plots check` with the keys imported and the test passed, no "missing key" warnings, proofs percentage is ok.
I've tried to downgrade harvester from 1.2.2 to 1.2.1 - no luck either.

So I want to know if anyone get accepted partials, or maybe the same errors as I have.

**Comment by harold-b** [comment]
Appreciate you bringing this up about pool plots. As mentioned in the readme, I've not been able to test them. I do have my wallet synced now so I am able to test pool plots. I will be having a look at this in the evening and report back findings here.

**Comment by mocksoul** [comment]
I did made 500+ plots with pooling api and can confirum everything works properly with them

**Comment by mocksoul** [comment]
Oops. I thought u talking about ProofOfSpace check +)

But after inspecting farmer logs I do also see such messages as mentioned in OP.

**Comment by harold-b** [comment]
OK, appreciate the feedback.

**Comment by harold-b** [comment]
Tracked the issue on memo/plot id generation process. Will post a fix in the coming hours.
Thanks for reporting this issue.

**Comment by harold-b** [comment]
This has been fixed in a990e2344e2fa228605e117c7e5bab87811cd0ea

**Comment by CharlieTemplar** [comment]
@harold-b, Is this in the master now if I update?  What is the nature of the wrong info, is there anything that can be done with pool plots already created with a version from before the fix? Or are they trash?  
Noticed this when partials submitted to pool did not increase...

**Comment by CharlieTemplar** [comment]
also is there any way to identify bad plots maybe with plots check --debug-show-memo??

**Comment by harold-b** [comment]
> Is this in the master now if I update?
Yes it's been merged to master. Unfortunately you will have to replot. Several in the community have tested the new ones and confirmed their validity. I also validated the fix generating the exact values from the chia-blockchain implementation, so those are safe. But the old ones you gotta replace.
