### ISSUE TITLE
Flush log output immediately

### ISSUE THREAD

**Issue by altendky** [harold-b/bladebit#78]
I am just now getting around to trying to add BladeBit support to plotman.  Generally speaking the multiple-process scheduling features of plotman should be much less useful for BladeBit, but it makes it easier for people to experiment with configurations and still handle plotting and archiving from the single tool.  Anyways...

When the output of BladeBit is redirected to a file it ends up buffering until the flush at the end (well, I didn't wait that long what with only 64GB of RAM at the moment but...).  plotman would like to have regular updates so that it can track the progress of the plot.  With the logging functions already being centralized it looks like this could be a straightforward change.

Does this seem like a good change for BladeBit?

**Comment by harold-b** [comment]
Nice to see you here, Kyle

Sure, @mocksoul already provided a PR for this. I merged it into the [develop](https://github.com/harold-b/bladebit/tree/develop) branch yesterday. I don't consider develop completely stable, but I don't believe there is any PR currently merged to it that would cause instability so you can try working off from that branch.

**Comment by altendky** [comment]
Ah, I forget to look around for separate release/dev branches...  `:|`  Thanks.  I'll give that a try once I get all my existing tests passing for BladeBit in plotman and actually start running it.

**Comment by altendky** [comment]
It did work, thanks again to both of you.  I did get a preliminary version of BladeBit support in plotman last night in https://github.com/ericaltendorf/plotman/pull/916.  Other than the automated tests, I am only aware of it having been run briefly on my insufficient laptop where it was able to launch and detect a BladeBit process.

**Comment by harold-b** [comment]
Thank you, Kyle! I appreciate you making this available for your vast community.
