### ISSUE TITLE
Fails to compile on Arm 

### ISSUE THREAD

**Issue by soothill** [harold-b/bladebit#79]
I am trying to compile this on an Oracle Cloud Ampere instance and am getting the following error message:-

src/threading/Thread.cpp
src/threading/ThreadPool.cpp
src/Util.cpp
src/util/Log.cpp
In function ‘compress_parents_parallel’,
    inlined from ‘compress_subtree_to_parent_node’ at src/b3/blake3.c:355:9,
    inlined from ‘blake3_hasher_update.part.0’ at src/b3/blake3.c:534:7:
src/b3/blake3.c:242:5: warning: ‘memcpy’ writing 32 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
     memcpy(&out[parents_array_len * BLAKE3_OUT_LEN],
     ^
In function ‘compress_subtree_to_parent_node’,
    inlined from ‘blake3_hasher_update.part.0’ at src/b3/blake3.c:534:7:
src/b3/blake3.c:356:5: warning: ‘memcpy’ reading between 64 and 96 bytes from a region of size 32 [-Wstringop-overflow=]
     memcpy(cv_array, out_array, num_cvs * BLAKE3_OUT_LEN);
     ^

**Comment by harold-b** [comment]
These are warnings, not errors. If it's failing to compile you might have grabbed the wrong snippet. Is there an error elsewhere?
